project_id = "lbcpqynztwwvatcviatc"

[functions.deepseek-chat]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.ai-interpret]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false
